"""
Use this script will process the raw MLX files by:
- combining all the MLX CSVs generated by the firmware into day or hour.
- combining the timestamp columns to create a 1 13 digit timestamp.
- applying a gaussian kernel to remove the checker board effect
"""
import os
import shutil
import numpy as np
import pandas as pd
import cv2
from datetime import datetime

from scipy import interpolate
from tqdm import tqdm
import matplotlib.pyplot as plt


def build_checkerboard(w, h):
    re = np.r_[w * [0, 1]]  # even-numbered rows
    ro = np.r_[w * [1, 0]]  # odd-numbered rows
    return np.row_stack(h * (re, ro))

def interpolate_image(row):

    img = row[1:].values
    img = img.reshape(24, 32)
    checkerboard = build_checkerboard(16, 12)
    sub_image = (img * checkerboard)
    sub_image[sub_image == 0] = None

    x = np.arange(0, sub_image.shape[1])
    y = np.arange(0, sub_image.shape[0])

    array = np.ma.masked_invalid(sub_image)
    xx, yy = np.meshgrid(x, y)
    x1 = xx[~array.mask]
    y1 = yy[~array.mask]
    new_array = array[~array.mask]

    try:
        img = interpolate.griddata((x1, y1), new_array.ravel(),
                               (xx, yy),
                               method='cubic')
    except:
        img = img * 0

    row[1:] = img.ravel()
    return row



##########################
main_dir = "/Users/rma145/Desktop/thermo-smoking/Data/angles_test/me/"
p = "RTC"
##########################


in_dir = main_dir + p + "/raw"  # the directory of the raw MLX files
out_dir = main_dir + p + "/clean"

if os.path.exists(out_dir):
    shutil.rmtree(out_dir)
os.makedirs(os.path.join(out_dir))

# geting the list of CSVs and sorting them
files = os.listdir(in_dir)
files = [int(f[:-4])for f in files if f.endswith(".csv")]
files.sort()



# looping though each csv file
for f in tqdm(files):

    # reading the csv
    data = pd.read_csv(os.path.join(in_dir,str(f)+".csv"),header=None)
    # all_hours = np.floor(((data[0].values)/3600)%24)
    all_datetmie = pd.to_datetime(data[0],unit='s')
    date = all_datetmie.dt.date.values.astype('str')[0]
    hour = all_datetmie.dt.hour.values.astype('str')[0]
    data[0] = (data[0] * 1000) + (data[1] % 1000) # creating 13 digit timestamp
    data = data.drop(1, axis=1) # removing mills


    # data = data.apply(interpolate_image,axis=1)





    # h_data_i = np.where(all_hours==h)
    # h_data = data.iloc[h_data_i]


    csv_name = os.path.join(out_dir, date + "_"+hour+".csv")
    data.to_csv(csv_name, mode='a', header=False, index=False)

    out_h_dir = os.path.join(out_dir, date + "_" + hour)
    os.makedirs(out_h_dir, exist_ok=True)
    for row in data.values:
        img_name = os.path.join(out_h_dir, str(int(row[0]))+".png")
        img = row[1:].reshape(24, 32)
        #cv2.imwrite(img_name, img)
        plt.imsave(img_name, img)







    # generating the 13 digit time stamp

    # generating images and saving them into hours folder

    # combining data into 1 hour CSV






